### ISSUE TITLE
大佬 麻烦了

### ISSUE THREAD

**Issue by wwr520** [a709691139/zhongshan-frontend-work#2]
中企育贝：公司是挂着国企的名号来招人，面试会问一下ajax什么的，有什么作品。但是进去后老板会无形地给压力你，每到节假日的前一天，你必会收到工作任务。之前说好的奖金也会泡汤，用都是老技术 jquery / apicloud，单双休，还有管理超乱

**Comment by a709691139** [comment]
ok
