### ISSUE TITLE
补充

### ISSUE THREAD

**Issue by chenjiejing** [a709691139/zhongshan-frontend-work#3]
中山超悦动力网络科技有限公司 
在西区天悦城旁边,人事很强势一直压工资,面试过程中还一直强调中山的这个三线城市工资水平怎么样怎么样,问自己在以前项目创造了什么价值,职业规划一大堆,但是最后竟然跟我说技术老大不在,叫我第 二次再去,单休,听说每年能调薪的人只有3%,年功奖200一年,做ERP系统!!!
中山联创工场 5.5k  西区富华道 单休
boss上写着6-8k 实际只能给到5.5k巨坑,有外包项目也有自己的项目,看起来有20-30人,面试前端的对vue几乎都不懂,几乎没问什么技术问,单休,据说有加班费,人事说你愿意的话通宵加班都可以.
中山市诚民科技 单休
在中山技术职业学院创新楼,办公室很小,团队四五个人左右,做小程序外包,套模板,大概一个月要做好一个项目,老板是中职毕业创业公司,工资是底薪+提成 底薪给多少看老板,提成的话看完成的时间有多长
一棵树 单休 7k
在紫马广场17楼,公共办公室,vue+java后台项目,前端没有
安乐窝 单休 
伊电园 jq项目,有响应式移动端,弹性上下班

**Comment by a709691139** [comment]
ok 感谢分享
